### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by adriens**

### CODE REVIEW

**Review by Dougniel — CHANGES_REQUESTED** [review]
On "❔ About" section, remove carriage return that seems accidental

**Comment by adriens** [comment]
> On "grey_question About" section, remove carriage return that seems accidental

I have removed the `h1` section of `j7zip`... is that what you're pointing ?

**Comment by Dougniel** [comment]
> > On "grey_question About" section, remove carriage return that seems accidental
> 
> I have removed the `h1` section of `j7zip`... is that what you're pointing ?

image

**Review by Dougniel — APPROVED** [review]

**Comment by adriens** [comment]
:zap:

**Pull request merged**
